# site settings
title: Atum Systems
subtitle: A product development agency
email: g@atumsystems.com
description: Product designers. Technology drives innovation.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://atumsystems.com # the base hostname & protocol for your site
author:
street_address: 7083 Hollywood Blvd
city: Los Angeles
state: CA
zip_code: 90028
country: United States of America
phone: (323) 555-5555

theme: just-the-docs

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/
googleplus_url: https://plus.google.com/u/0/+
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/

# build settings
markdown: kramdown

sass:
  style: compressed
